E.toArrayBuffer(
    atob(
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/wAAAAAA//+AAAAAD///gAAAAP8Af4AAAAfgAD8AAAB+AAA/AAAD4PgAPgAAHw/gAHwAAPB8AAB4AAOHgAAQ4AAeOB4AI8AA8cP8BEeAA44f8AiOAB4x/8ATPABxj/8ERnADxGf8CZngDiMf8CIjgDiI38BMzgHkRD8BMzwHEQB8BsRwHEiA8A8ZwHAAA+B8ZwHAAAiP8ZwHAAAj/8ZwHAABj/8ZwHAAB//85wHAAH4/85wHAAfwP8xwHgA/gD8zwDgD/gA5zgDgH/gABjgDwH/gAAHgBwD/gAAHAB4R/wAAPAA4Y//gAOAA8cfAAAeAAeeHwAA8AAOHB/wA4AAPDwHgB4AAHx8AAHwAAD4fgEPgAAB+D/g/AAAA/gAD8AAAAP8Af4AAAAD///gAAAAA//+AAAAAAH/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
    )
  )
